server:
  port: 8002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.10.102.163:3306/library?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: 119.29.172.177
    port: 6379



mybatis:
  type-aliases-package: com.library.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#配置打印sql
#参考类：org.apache.ibatis.session.Configuration
#log-impl指定的值为org.apache.ibatis.logging.Log接口的某个实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  configuration:
    secretKey: library-public
    ttl: 1800000