server:
  port: 8001

spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql:///library?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 119.29.172.177
    port: 6379


mybatis:
  type-aliases-package: com.library.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  configuration:
    secretKey: library-public
    ttl: 1800000